name: ML
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=2.0.1
  - pandas=2.2.3
  - scipy=1.15.3
  - numexpr=2.10.1
  - bottleneck=1.4.2
  - python-dateutil=2.9.0
  - pytz=2024.1
  - tzdata=2025b
  - tabulate=0.9.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - joblib=1.5.1
  - scikit-learn=1.6.1
  - packaging=25.0
  - pip:
      - scikit-learn-extra @ git+https://github.com/TimotheeMathieu/scikit-learn-extra@21f5aa70c18e4615aaf700905014e9bf84c0d4f3